name: composer_example
services:
  say_hello_world:
    profiles: ["jobs"]
    image: "alpine:3.12"
    command: sh /say_hello.sh
    stdin_open: true
    tty: true
    volumes:
      - ./say_hello.sh:/say_hello.sh
    labels:
      # run this service every thirty seconds
      - "co.architect.composer.run=*/30 * * * * *"
      - "co.architect.composer.notify.slack=true"
      - "co.architect.composer.notify.slack.on-error=true"

  repeat_myself:
    image: "alpine:3.12"
    command: sh /test.sh
    stdin_open: true
    tty: true
    environment:
      - MY_ENV_VAR=${MY_ENV_VAR}
    volumes:
      - ./test.sh:/test.sh:ro
    labels:
      # restart this service every minute
      - "co.architect.composer.restart=0 * * * * *"
      - "co.architect.composer.notify.slack=true"

  scheduler:
    image: "afintech/composer:latest"
    environment:
      # recommended to set log level to debug
      - RUST_LOG=composer=debug
      - COMPOSE_PROJECT_DIRECTORY=${PWD}
      - COMPOSE_RUN_LOGS=/var/log/composer
      - HOST=my-host
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SLACK_WEBHOOK_ON_ERROR_URL=${SLACK_WEBHOOK_ON_ERROR_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # mount in the docker compose configuration
      - ./compose.yml:/compose.yml:ro
      # mount in the env file used by docker compose (optional)
      - ./.env:/.env:ro
      # mount in logs directory for run logs
      - ./var/logs:/var/log/composer:rw
